### ISSUE TITLE
Shared Properties

### ISSUE THREAD

**Issue by cyouh95** [Perdudum/codecademy_dasmoto_project#2]
For universal properties shared among all elements, you could use the `body` tag as selector (as all children elements would automatically inherit these properties):

```css
body {
  font-family: Helvetica, sans-serif;
  font-weight: bold;
}
```

https://github.com/Perdudum/codecademy_dasmoto_project/blob/master/resources/css/style.css
